name: AI Chatbot Update Workflow

on:
  push:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-ai-chatbot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Set this to your project's required Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: node scripts/embedTutorials.js
